### PR TITLE
Service Access Policies

### PR DESCRIPTION
**Pull request by sez11a**
Please add summary section and any related topics.

### CODE REVIEW

**Comment by sez11a** [comment]
Wordsmithed and superseded by https://github.com/jrao/liferay-docs/pull/65

**Comment by sez11a** [comment]
Sorry; closed the wrong one. :-)

**Comment by jrao** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jrao** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/1351

**Pull request closed without merging**
